#!/usr/bin/env python3
"""
build-doc-css.py — Externalize inline <style> blocks from internal docs.

Scans every in-scope HTML under dev/{plans,adr,audit,notes,feature_bank},
plus dev/ast-walk-diagram.html, reads the <style>...</style> body from
**git HEAD** (so re-running after a previous rewrite still works), and
writes a merged dev/assets/doc.css ordered most-common-block-first so the
cascade's last-wins behavior favors the long tail of one-off blocks.

Pair with dev/scripts/rewrite-html-link.py:
    python3 dev/scripts/build-doc-css.py        # produce dev/assets/doc.css
    python3 dev/scripts/rewrite-html-link.py    # rewrite HTMLs to <link>

Files explicitly skipped:
  - dev/adr/0013-*.html and dev/plans/0013-*/*.html
    (held for a concurrent worktree; revisit when 0013 lands)
  - dev/demo/demo.html (pandoc-generated, self-contained)
  - README.html, vignettes/*.html, archive/*.html (generated from .Rmd)
"""
import re, hashlib, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def in_scope_files() -> list[str]:
    paths: list[Path] = []
    for d in ("dev/plans", "dev/adr", "dev/audit", "dev/notes", "dev/feature_bank"):
        paths.extend((ROOT / d).rglob("*.html"))
    paths.append(ROOT / "dev/ast-walk-diagram.html")
    rels = []
    for p in paths:
        if not p.is_file():
            continue
        rel = p.relative_to(ROOT).as_posix()
        if rel.startswith("dev/adr/0013-"):
            continue
        if rel.startswith("dev/plans/0013-"):
            continue
        rels.append(rel)
    rels.sort()
    return rels


def git_show_head(relpath: str) -> str:
    try:
        return subprocess.check_output(
            ["git", "show", f"HEAD:{relpath}"],
            cwd=ROOT, text=True
        )
    except subprocess.CalledProcessError:
        return ""


def main() -> int:
    style_re = re.compile(r"<style>(.*?)</style>", re.DOTALL)
    scope = in_scope_files()
    blocks: dict[str, list[str]] = {}

    for rel in scope:
        head_text = git_show_head(rel)
        text = head_text if head_text else (ROOT / rel).read_text()
        m = style_re.search(text)
        if not m:
            print(f"WARN: no <style> in {rel}", file=sys.stderr)
            continue
        body = m.group(1).strip("\n")
        blocks.setdefault(body, []).append(rel)

    sorted_blocks = sorted(
        blocks.items(),
        key=lambda kv: (-len(kv[1]), hashlib.sha256(kv[0].encode()).hexdigest()),
    )

    out = []
    out.append("/* dev/assets/doc.css")
    out.append(" * Auto-generated by dev/scripts/build-doc-css.py.")
    out.append(" * Source: inline <style> blocks across dev/{plans,adr,audit,notes,feature_bank}")
    out.append(" *         HTMLs (+ dev/ast-walk-diagram.html), read from git HEAD.")
    out.append(" * Order: most-frequent block first; cascade last-wins covers the long tail.")
    out.append(f" * Buckets: {len(blocks)} unique CSS blobs across {sum(len(v) for v in blocks.values())} files.")
    out.append(" * Do not hand-edit — re-run the script after changing inline styles in source HTML.")
    out.append(" */")
    out.append("")

    for body, files in sorted_blocks:
        h = hashlib.sha256(body.encode()).hexdigest()[:8]
        out.append(f"/* ---- source bucket {h} ({len(files)} file{'s' if len(files)!=1 else ''}) ----")
        for src in files[:6]:
            out.append(f" *   {src}")
        if len(files) > 6:
            out.append(f" *   ... and {len(files)-6} more")
        out.append(" */")
        out.append(body)
        out.append("")

    target = ROOT / "dev/assets/doc.css"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(out) + "\n")
    print(f"wrote {target.relative_to(ROOT)}: {len(blocks)} unique blocks, {sum(len(v) for v in blocks.values())} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
